databasePath = "database/"
startUpFile = databasePath + "SU1.su"
passwordFile = databasePath + "passfap.txt"
publicKeyPath = databasePath + "publicKey.pem"
privateKeyPath = databasePath + "privateKey.pem"